### ISSUE TITLE
Issue with PHP 7.0

### ISSUE THREAD

**Issue by jarekkantor** [ciaranmcnulty/behat-localwebserverextension#3]
Unfortunatelly extension doesn't work with PHP 7.0 because of the restriction in composer.json. Composer returns the below message in PHP 7.0 environment:

  Problem 1
    - Installation request for ciaranmcnulty/behat-localwebserverextension 1.1.0 -> satisfiable by ciaranmcnulty/behat-localwebserverextension[1.1.0].
    - ciaranmcnulty/behat-localwebserverextension 1.1.0 requires php ~5.4 -> your PHP version (7.0.1-1+deb.sury.org~trusty+2) or value of "config.platform.php" in composer.json does not satisfy that requirement.

**Comment by ciaranmcnulty** [comment]
Yes good point

**Comment by ciaranmcnulty** [comment]
I've released `1.1.1` with PHP 7 support - let me know if it works for you

**Comment by jarekkantor** [comment]
It's not working, see the message below:

Problem 1
    - Installation request for ciaranmcnulty/behat-localwebserverextension ^1.1.1 -> satisfiable by ciaranmcnulty/behat-localwebserverextension[1.1.1].
    - ciaranmcnulty/behat-localwebserverextension 1.1.1 requires php ~5.4,~7.0 -> your PHP version (7.0.1-1+deb.sury.org~trusty+2) or value of "config.platform.php" in composer.json does not satisfy that requirement

Changing PHO requirement to the below should fix that:
"php" : ">=5.4"

**Comment by ciaranmcnulty** [comment]
OK I mangled the composer.json. Can you try a composer update now please?

**Comment by jarekkantor** [comment]
Everything's ok now! Thanks!

**Comment by thomasmagestore** [comment]
I couldn't run this command: composer install. Can I use the library magestest/behat for PHP 7.0 and magento 2.2.1? Help me please.

**Comment by ciaranmcnulty** [comment]
@thomasmagestore I suggest asking on that project’s issues

**Comment by thomasmagestore** [comment]
@ciaranmcnulty I want to test the functional of my website before I release.

**Comment by ciaranmcnulty** [comment]
Oh are asking about the platform requirements of a library I don’t use. Ask them

**Comment by thomasmagestore** [comment]
@ciaranmcnulty it should be like Functional Testing. But I want to apply BDD or behat for testing Magento site. Do you have any equivalent like this.
